version: "3"

services:
  rstudio:
    container_name: rstudio_container
    restart: always
    build:
      context: ./R_env
    volumes:
      - ./../main:/home/rstudio/main
      - ./../playground:/home/rstudio/playground
      - ./../data:/home/rstudio/data
      - ./../src:/home/rstudio/src
      - ./../reports:/rstudio/reports
      - ./../docker_env/R_env:/rstudio/env
    ports:
      - "8787:8787"
    environment:
      USER: "rstudio"
      DISABLE_AUTH: "TRUE"
      ROOT: "TRUE"
      PASSWORD: "r"
  jupyter:
    container_name: jupyter_container
    restart: always
    build:
      context: ./python_env
    volumes:
      - ./../main:/home/main
      - ./../playground:/home/playground
      - ./../data:/home/data
      - ./../src:/home/src
      - ./../reports:/home/reports
      - ./../docker_env/python_env:/home/env
    ports:
      - "8888:8888"
    environment:
      ROOT: "TRUE"
      TZ: Asia/Tokyo
    command: "/opt/conda/bin/jupyter lab --notebook-dir=/home/main"
  postgres:
    container_name: postgres_container
    restart: always
    image: postgres:12.1
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: Asia/Tokyo
    ports:
      - 5432:5432
    volumes:
      - ./../data/db:/var/lib/postgresql/data
      - ./../data/db:/var/lib/postgresql/data
      # - ./../data/db_init:/docker-entrypoint-initdb.d/
  pgAdmin:
    container_name: pgAdmin_container
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8000:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin
      PGADMIN_DEFAULT_PASSWORD: pgadmin
      volumes:
      - ./../data/db:/root/.pgadmin
